# Stubs for mlconjug (Python 3.6)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from .mlconjug import *
from .PyVerbiste import *
from typing import Any

__author__: str
__email__: str
__version__: str
RESOURCE_PACKAGE = __name__
TRANSLATIONS_PATH: Any
SUPPORETD_LANGUAGES: Any
windll: Any
user_locale: Any
MLCONJUG_TRANSLATIONS: Any

def getdoc(object: Any): ...
