# Stubs for mlconjug.cli (Python 3.6)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from .mlconjug import Conjugator
from typing import Any

def main(verb: Any, language: Any) -> None: ...
