# Stubs for mlconjug.mlconjug (Python 3.6)

from .PyVerbiste import Verb, Verbiste
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.base import BaseEstimator
from typing import Any, Optional, Text, Dict, List, DefaultDict, KeysView, Union


_RESOURCE_PACKAGE: Text = __name__
_LANGUAGE_FULL: Dict[Text, Text]
_VERBS: Dict[Text, Verb]
_PRE_TRAINED_MODEL_PATH: Dict[Text, Text]


class Conjugator:
    language: Text = ...
    verbiste: Verbiste = ...
    data_set: DataSet = ...
    model: Model = ...
    def __init__(self,
                 language: Text = ...,
                 model: Optional[Model] = ...
                 ) -> None: ...

    def __repr__(self) -> Text: ...

    def conjugate(self,
                  verb: Text,
                  subject: Text = ...
                  ) -> Optional[Verb]: ...

    def set_model(self,
                  model: Model
                  ) -> None: ...


class EndingCountVectorizer(CountVectorizer):
    def _char_ngrams(self,
                     verb: Text
                     ) -> List[Text]: ...


class DataSet:
    verbiste: Verbiste = ...
    verbs: KeysView[Text] = ...
    templates: List[Text] = ...
    liste_verbs: List[Text] = ...
    liste_templates: List[int] = ...
    dict_conjug: DefaultDict[Text,List[Text]] = ...
    train_input: List[Text] = ...
    train_labels: List[int] = ...
    test_input: List[Text] = ...
    test_labels: List[int] = ...
    min_threshold: int = ...
    split_proportion: float = ...
    def __init__(self,
                 VerbisteObj: Verbiste
                 ) -> None: ...

    def __repr__(self) -> Text: ...

    def construct_dict_conjug(self) -> None: ...

    def split_data(self,
                   threshold: int = ...,
                   proportion: float = ...
                   ) -> None: ...

class Model:
    model: Model = ...
    def __init__(self,
                 vectorizer: Optional[Union[EndingCountVectorizer, CountVectorizer]] = ...,
                 feature_selector: Optional[BaseEstimator] = ...,
                 classifier: Optional[BaseEstimator] = ...
                 ) -> None: ...

    def __repr__(self) -> Text: ...

    def train(self,
              samples: List[Text],
              labels: List[int],
              ) -> None: ...

    def predict(self,
                verbs: List[Text]
                ) -> Optional[Verb]: ...
